"""What kind of DGLAP is the two-C row: PDF-type or fragmentation-type?"""
import sympy as sp
K,P=sp.symbols('kplus pplus',positive=True); S=P+K
z_=sp.symbols('zeta',positive=True); kt=sp.Symbol('k_perp',positive=True)
print("="*76); print("1.  WHAT IS THE PHASE CONJUGATE TO?"); print("="*76)
print("   the two C deltas gave   w - z = (S/k+)(y - z) ,  w' - z = (S/k+)(y' - z),")
print("   hence  w' - w = (S/k+)(y' - y) = (S/k+) r   and")
print("      e^{-ik.(w'-w)} = e^{-i (S/k+) k.r}")
print("   with zeta = k+/S :   S/k+ = 1/zeta , so")
print("      e^{-ik.(w'-w)} = e^{-i (k_perp/zeta).r}")
print("   substitution check  S/k+ with S = k+/zeta :", sp.simplify((K/z_)/K))
print()
print("   => r = y'-y is conjugate to  k_perp/zeta ,  NOT to k_perp.")
print("      k_perp/zeta is the PARENT's transverse momentum: if the splitting is")
print("      collinear the daughter carries zeta of both + and transverse momentum,")
print("      so k_perp^parent = k_perp/zeta.")
print()
print("   THIS IS THE FRAGMENTATION SIGNATURE: the hard factor is evaluated at k/zeta,")
print("   not at k.  A PDF-type (initial-state) collinear log would leave the hard")
print("   factor at the measured k and put the zeta convolution on the incoming flux.")

print(); print("="*76); print("2.  AND THE MEASURE"); print("="*76)
print("   we found   dp+ = k+ d zeta / zeta^2   at fixed k+, giving  int d zeta/zeta^2 .")
print("   the standard collinear fragmentation formula for the INVARIANT cross section is")
print("      E dsigma^h/d^3k = sum_i int_x^1 (dz/z^2) D_{h/i}(z) [E' dsigmahat^i/d^3k']_{k'=k/z}")
print("   -- the same dz/z^2.   A PDF convolution instead carries dxi/xi with the parton")
print("   density, not dz/z^2 with the hard factor shifted to k/z.")
print()
print("   so all three kinematic signatures line up with FRAGMENTATION:")
print("      (a) coefficient P_gg(zeta),  zeta = fraction of the PARENT taken by the")
print("          MEASURED gluon;")
print("      (b) measure d zeta/zeta^2 ;")
print("      (c) hard factor at k/zeta (through the phase).")

print(); print("="*76); print("3.  WHERE THE COLLINEAR REGION SITS"); print("="*76)
q=sp.Symbol('q',positive=True)
print("   two final-state gluons k (measured) and p (unobserved) are collinear when")
print("      M^2 = (p+ k_perp - k+ p_perp)^2/(p+ k+)  -> 0 ,  i.e. relative q_perp -> 0.")
print("   small relative q_perp  <=>  LARGE relative transverse separation.")
print("   that is exactly where the two-C row diverges (|z| -> infinity), and NOT at any")
print("   collapse of points.  Final-state collinear singularities live at large distance;")
print("   ultraviolet ones live at small distance.  The row has the first and not the second.")
