"""Row 14/15: does the AC x B_2 interference row produce a DGLAP logarithm?"""
import sympy as sp, numpy as np
z_=sp.symbols('zeta',positive=True); zb=1-z_
S=sp.Symbol('S',positive=True); K=S*z_; P=S*zb
dp=sp.Symbol('d_perp')
Cuv = z_/zb + zb/z_ + z_*zb
print("="*78); print("THE TEST (as it worked for the two-C row)"); print("="*78)
print("   DGLAP needs BOTH:")
print("     (i)  a transverse (collinear) logarithm -- in the two-C row this was")
print("          Lcal = 1/eps - log(4 pi^2 mu^2 r^2) from the log-divergent z integral;")
print("     (ii) its coefficient equal to C_UV(zeta) = zeta/zetabar + zetabar/zeta + zeta zetabar")
print("          = P_gg(zeta)/(2 Nc),  zeta = k+/(p+ + k+).")
print()
print("="*78); print("(i)  IS THERE A COLLINEAR LOGARITHM?   -- NO"); print("="*78)
print("   This row has NO transverse divergence at all:")
print("     * no UV: all 26 collapsing subsets of {x,x',y',z,w} converge;")
print("     * no IR in z: the C delta leaves the phase e^{-ik (p+/k+)(y'-z)}, which damps")
print("       the z integral.  Measured: |A(R)| R^2 = 6.1e-2, 1.6e-2, 5.4e-3 at R = 1e2,1e3,1e4.")
print("   With no divergent transverse integral there is no 1/eps and no log(mu^2 r^2)")
print("   for a splitting function to multiply.  Contrast the two-C row, where")
print("   int d^2z of two WW kernels WAS log divergent and produced exactly that log.")
print()
print("="*78); print("(ii) WHAT zeta-DEPENDENCE DOES SURVIVE?"); print("="*78)
print("   The only transverse logarithm anywhere in this row is the one welded to the")
print("   rapidity log by the Ei:   Ei(-i kappa Lambda) -> gamma + log(|kappa| Lambda),")
print("     log(|kappa| Lambda) = log(Lambda) + log( |k.(y'-z)|/k+ ).")
print("   Its coefficient is the 1/p+ structure of the contraction.  Which terms carry 1/p+?")
print()
print("   T^{k'm} = (p+/S) d_{k'm} tr M  -  M^{k'm}  -  (p+/k+) M^{m k'},")
print("   M = d^{ij}(A-B)/(2 S C) + K^{ij}/k+ + P^{ij}/p+ :")
print("     (p+/S) d tr M  ->  (p+/S)(tr P)/p+ = (tr P)/S          no 1/p+")
print("     -M^{k'm}       ->  -P^{k'm}/p+                          YES")
print("     -(p+/k+)M^{mk'}->  -(p+/k+) P^{mk'}/p+ = -P^{mk'}/k+    no 1/p+")
print("   so the rapidity/transverse log rides on the SINGLE structure  -P^{k'm}/p+ ,")
print("   whose coefficient in zeta is")
c = sp.simplify(1/P)
print("        1/p+ = 1/(S zetabar) =", sp.simplify(c))
print("   i.e. a PURE SOFT POLE 1/zetabar -- only the zeta -> 1 end of P_gg, with no")
print("   zetabar/zeta and no zeta zetabar partner.  Not a splitting function.")
print("   difference from C_UV :", sp.simplify(sp.expand(1/zb - Cuv)))

print()
print("="*78); print("(iii) AND THE ONE OTHER TRANSVERSE LOG: large |x|"); print("="*78)
print("   |x| -> infinity IS log divergent, but x is a rho position, cut by the source,")
print("   so that log runs between the source size and the other transverse scales --")
print("   the one place a collinear log could legitimately hide.  Measure its zeta")
print("   dependence directly (row15_xlog.py); an analytic angular limit is easy to get")
print("   wrong, and mine was.")
print()
print("      %-9s %12s %13s %10s" % ("zeta","plateau","C_UV(zeta)","ratio"))
for zt,v,c in [(0.86957,1.07299934,6.930088),(0.72993,0.28706555,3.269836),
               (0.58824,0.06547661,2.370786),(0.40000,-0.05121049,2.406667),
               (0.25000,-0.11436854,3.520833),(0.14286,-0.15637714,6.289116)]:
    print("      %-9.5f %12.8f %13.6f %10.6f" % (zt,v,c,v/c))
print()
print("   the ratio CHANGES SIGN near zeta = 1/2 (p+ = k+).  P_gg(zeta) is positive on")
print("   (0,1), so this coefficient cannot be a splitting function.   NOT DGLAP.")
