#!/usr/bin/env python3
"""Inline all \\input{...} files of NLO_gluon_midrapidity.tex into one file.

    python3 flatten.py      # writes NLO_gluon_midrapidity_flat.tex

The single-file version compiles on its own (e.g. on Overleaf or arXiv).
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
MAIN = "NLO_gluon_midrapidity"
OUT = MAIN + "_flat.tex"


def expand(name, depth=0):
    fn = os.path.join(HERE, name if name.endswith(".tex") else name + ".tex")
    with open(fn) as f:
        text = f.read()
    if depth > 5:
        return text

    def inline(m):
        inner = m.group(1)
        body = expand(inner, depth + 1).rstrip()
        return f"%% >>> begin {inner}.tex\n{body}\n%% <<< end {inner}.tex"

    # only \input commands at the start of a line (never inside comments)
    return re.sub(r"(?m)^\\input\{([^}]+)\}", inline, text)


def main():
    text = expand(MAIN)
    text = text.replace(
        "%%  Open items of the calculation",
        "%%  Single-file version generated by flatten.py: all sections and\n"
        "%%  appendices are inlined. Edit the multi-file sources instead.\n"
        "%%\n"
        "%%  Open items of the calculation",
        1,
    )
    with open(os.path.join(HERE, OUT), "w") as f:
        f.write(text)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
