import static_tex as st
import make_tex

CHECKS = r"""
\section{Checks}\label{app:checks}
The algebra was generated by a short program, which also checked it numerically.
\begin{enumerate}
\item \emph{Reordering identity.} Eqs.~\eqref{eq:plain}--\eqref{eq:antiA}, including the explicit one-$\rho$ remainder $R_1$, hold to machine precision for random matrices $A,B,C$.
\item \emph{Colour algebra.} Each of the 144 pieces was evaluated before and after the colour algebra, for $SU(3)$ with random classical charges and random symmetric adjoint Wilson lines ($U$ of $V=W\,{\rm diag}(1,-1,-1)\,W^\dagger$, $W$ random). The two agree to $2\times10^{-15}$ for every piece. With general, non-symmetric Wilson lines, 14 pieces differ. These are exactly the pieces whose simplification uses (U1$^\star$) or (U2$^\star$), i.e.\ the convention $U^{bc}=U^{cb}$.
\item \emph{The whole reordering.} For every sub-term we took the charges as explicit operators on three sites (the $\delta$-function becomes a Kronecker delta), with random kernels and random symmetric Wilson lines. We then compared
\begin{equation*}
\sum_{\rm singlets}\langle s|\,O-S(O)\,|s\rangle\qquad\text{and}\qquad\sum_{\rm singlets}\langle s|\,(\text{two-}\rho\text{ pieces})\,|s\rangle ,
\end{equation*}
where $O$ is the three-$\rho$ operator of the sub-term, $S(O)$ its fully symmetrized form, and $|s\rangle$ runs over the colour singlets, in which every one-$\rho$ term has zero expectation value. We used $SU(3)$ with one quark per site (one singlet) and $SU(2)$ with two spin-$\frac12$ per site (five singlets), three random draws each. The largest difference was $4\times10^{-14}$, for values up to $25$. This checks the commutators, the signs, the factors $\frac14$ and $\frac12$, the $\delta$-functions and the colour algebra together.
\end{enumerate}
"""

body, summ, res = make_tex.main()
doc = st.PREAMBLE + st.INTRO + st.CONVENTIONS + st.IDENTITY + body + '\n' + summ + '\n' + st.APPF + CHECKS + '\n\\end{document}\n'
open('ThreeRho_to_TwoRho.tex', 'w').write(doc)
print('ok', len(doc))
